### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Fancy2209** [OpenPlayerIO/ResolvePIO#1]
Hello, the site is down and the discord invite is invalid, is this on purpose?
I was looking into making a Server replacement for Last Stand Dead Zone based on OPIO so I wanted to ask a few questions, but can't find a valid server invite

**Comment by atillabyte** [comment]
Hi there.

Thanks for your interest in the project. Feel free to reach me via discord with any questions you may have (@whiskrs)
